export const typography = {
  fonts: {
    sans: ['Google Sans', 'Google Sans Text', 'Product Sans', 'sans-serif'],
    display: ['Google Sans Display', 'Google Sans', 'Google Sans Text', 'Product Sans', 'sans-serif'],
    label: ['Open Sans', 'sans-serif'],
  },
  scale: {
    'type-hero': ['3rem', { lineHeight: '1', letterSpacing: '-0.5px', fontWeight: '700' }],
    'type-section-heading': ['1.5rem', { lineHeight: '1.2', fontWeight: '700' }],
    'type-nav-brand': ['1.125rem', { lineHeight: '1.2', letterSpacing: '-0.45px', fontWeight: '700' }],
    'type-body': ['1rem', { lineHeight: '21.6px', fontWeight: '400' }],
    'type-meta': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
    'type-label': ['0.875rem', { lineHeight: '1rem', letterSpacing: '1.4px', fontWeight: '500' }],
    'type-copyright': ['0.75rem', { lineHeight: '1rem', letterSpacing: '2.4px', fontWeight: '400' }],
    'type-badge': ['10px', { lineHeight: '1rem', fontWeight: '600' }],
    'type-caption': ['11px', { lineHeight: '1rem', fontWeight: '600' }],
    'type-field': ['13px', { lineHeight: '1.25rem', fontWeight: '400' }],
    'type-field-md': ['0.95rem', { lineHeight: '1.5rem', fontWeight: '400' }],
    'type-heading-md': ['2rem', { lineHeight: '1.2', fontWeight: '400' }],
    'type-heading-sm': ['22px', { lineHeight: '1.75rem', fontWeight: '600' }],
    'type-toast': ['14px', { lineHeight: '1', fontWeight: '500' }],
  },
  tracking: {
    label: '0.14em',
    labelWide: '0.18em',
    labelNarrow: '0.12em',
    labelExtraWide: '0.2em',
    labelMid: '0.16em',
  },
}
